### ISSUE TITLE
jmt(ics23): add proptests for each nonexistence setups

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/jmt#104]
The ICS23 adjacency calculation can happen over three types of configurations reflected in `ics23::NonExistenceProof`, indeed, either the queried key has:
- only a right neighbor (leftmost key)
- only a left neighbor (rightmost key)
- or both

As part of our #103 effort, we should add prop tests that take advantage of the `TransparentHasher` to test each configurations with arbitrary depth.

              One nit, inline, and a thought: can we capture the essence of these unit tests as a proptest?

_Originally posted by @plaidfinch in https://github.com/penumbra-zone/jmt/pull/100#pullrequestreview-1653695421_

**Comment by erwanor** [comment]
One thought: if we want to test that the bounding path calculations are correct, we could generate a sorted vector of key hashes $\langle k_1, k_2, ..., k_n \rangle$ (using the `TransparentHasher`), load them, and then iterate over each key hash $k_i$, mask the last nibble and query the jmt for a proof. What we should obtain as a result is a nonexistence proof for $(k_{i-1}, k_{i+1})$.

**Comment by aubrika** [comment]
Not adding to V1 currently for scope management but could be elevated if partially done
