### ISSUE TITLE
ICS23 support

### ISSUE THREAD

**Issue by aubrika** [penumbra-zone/jmt#18]
1. Update existing `tmp-jmt` branch implementation to use updated `jmt main` sha2 implementation, including updating tests & verify function
2. Implement ProofSpec using above verifier as reference verifier

**Comment by aubrika** [comment]
The inclusion proofs are implemented, but the parts of the proof spec describing non-inclusion proofs are currently stubbed, because we can't meaningfully do non-inclusion proofs until we have #24.

**Comment by plaidfinch** [comment]
@aubrika @avahowell Now that deletion is implemented, is it time to revisit non-inclusion proofs?

**Comment by hdevalence** [comment]
Long-delayed update to this: we need https://github.com/cosmos/ics23/pull/136 to be merged upstream, and then we're done.  Currently, the `main` branch points at a PR fork, which will prevent us from releasing the crate until the changes are included upstream.  In the meantime, if there are delays, and we have other features (e.g., as part of #74), we might have to do some juggling.

**Comment by zbuc** [comment]
https://github.com/cosmos/ics23/pull/136 is expected to be merged soon

**Comment by conorsch** [comment]
Still waiting on merge above, and then a subsequent release to be cut upstream. Then we'll cut a new release of our own shipping the feature.

**Comment by conorsch** [comment]
Status update: upstream PR is merged, upstream has released a new version, our jmt crate has also received a version bump, but there's still one more version bump incoming by @erwanor before we update and integrate into Penumbra, via https://github.com/penumbra-zone/penumbra/pull/2032

**Comment by erwanor** [comment]
This is still pending on a new release of `ibc-proto-rs`, but recent developments on the `cosmos/ics23` makes this imminently unblocked.

**Comment by redshiftzero** [comment]
Closed by https://github.com/penumbra-zone/penumbra/pull/2628
