### ISSUE TITLE
ROOT_NIBBLE_HEIGHT is wrong

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/jmt#20]
`ROOT_NIBBLE_LENGTH` was formerly `HashValue::LENGTH * 2`; this was updated to `256 * 2` instead of `32 * 2` as part of the byte-oriented refactoring.  We should identify exactly where this happened and whether there were any other errors made a the same time as this one.

**Comment by aubrika** [comment]
This change happened in #15 , here:

https://github.com/penumbra-zone/jmt/pull/15/files#diff-a24d89da14b71cd283dbe8cf1d4412177027cbe2beea657dc6e5f50cb0e517ac

There are a couple remaining references to `diem_crypto::hash::HashValue` in `access_path.rs` and `block_info.rs`, but code from those files doesn't seem to be referenced anywhere else.

**Comment by aubrika** [comment]
https://github.com/penumbra-zone/jmt/pull/28 fixes `ROOT_NIBBLE_HEIGHT` itself so far, but I want to make a survey of changes in #15 and look for places where `HashValue::LENGTH` might have been replaced incorrectly.
