### ISSUE TITLE
Tracking: `jmt` changes required for Penumbra state model V3

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/jmt#50]
In order of priority:

- [x] #51
- [x] #24 

#51 is a performance optimization that can be performed before or after any other work, and seems not to have a strong time preference. It doesn't seem to @aubrika and myself that this would be *harder* after implementing #24, and since #24 is needed for ICS23, it seems preferable to prioritize that.

**Comment by hdevalence** [comment]
That priority order is reversed: we need to **revert** the async changes, so we should not make further changes on top of them.

**Comment by plaidfinch** [comment]
Both are completed on `newmain`.
