### ISSUE TITLE
Roll back to pre-`async` code

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/jmt#51]
We modified the original JMT code to use an `async` interface instead of a synchronous one. This was, ultimately, a mistake. Because we're using RocksDB, which does not provide an asynchronous API, our implementation of the tree reader / writer traits uses `spawn_blocking` internally.  But this is strictly less efficient than wrapping the tree accesses in a single `spawn_blocking` call at the top level, and makes all of the code more complicated.

**Comment by hdevalence** [comment]
In order to do this, we'll need to compile a list of changes we made after the async rewrite, so that after resetting history to the pre-async state, we can backport or reapply those changes.

**Comment by hdevalence** [comment]
This is now in `newmain`.  The substantive changes that have not been backported are:

1. The `WriteOverlay` -- we should not backport this, because we'll roll it up into State V3 in the Penumbra crates;
2. Commit 11925d6 #45 , which skips generating proofs in `get`.

Otherwise, we're good to go.
