### ISSUE TITLE
Large stored values likely lead to unnecessary read load

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/jmt#61]
The way leaf nodes are designed doesn't seem like it will perform very well if the stored values are large. Because values are embedded directly in leaf nodes, operations that nominally only need to manipulate the structure of a node will end up loading all of the data from the value. One example of this is when an insertion happens in a leaf node: this should not require pulling all the leaf node's attached value data from disk, but it does.

Maybe this was an acceptable design for Diem because the values were mostly things like account balances, which are small, but our values are sometimes larger structured data like compact blocks. This probably has a performance impact—path compression means that when you insert, you are always going to subordinate an existing leaf to a newly created internal node somewhere, so you always have to load a leaf's data that you didn't need to. We could benchmark this by instrumenting the `MockTreeStore` to record _number of bytes_ written and read.

It's worth noting that we don't have to write back the value of the leaf unless it changes, because we can reuse the same node jet as the child of a newly created internal node, so it's primarily read volume and memory usage that is negatively affected by this design.

Another level of indirection would solve this: it would penalize every `get` operation by one extra database query, but would reduce the memory usage and read volume proportionate to the size of the values we store. The way we would do this would be to add another kind of node, a `Payload` node, with tag 4, that holds the actual value contained in a leaf. Every leaf would have a `NodeKey` that points to its payload. Updating a leaf's payload would require only updating the `Payload` node, not the leaf node itself. This would mean that no matter how large a leaf's associated data, manipulating parts of the tree that touch that leaf doesn't require loading the leaf's payload unless we explicitly need it during a `get` operation for that leaf itself.

**Comment by zbuc** [comment]
This is fixed already.

The reason `pd` isn't on JMT 0.4 is because we have to change our RocksDB usage because the leaf DB values are separated out.
